title: Jesus Vera Callme # your name (or website title) here
logo: "/images/3x4.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelor in Computer Science
  <br><br>
  Graduated from the Catholic University of San Pablo, Arequipa, Peru
  <br><br>
  <a href="https://www.linkedin.com/in/jesus-vera-callme-557214197/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
